/**
 * .sh exporter (§3.3, P4-FR-16b): POSIX script with env vars + exec.
 * Output is deterministic — golden-file tested (P4-NFR-01 spirit).
 */

import type { BuiltCommand } from "../flags/builder";
import {
	formatCommand,
	formatEnvValue,
	isValidEnvKey,
	sanitizeTextLine,
} from "./quote";

export interface ShellScriptInput {
	built: BuiltCommand;
	envVars: Record<string, string>;
	presetName: string;
}

export function buildShellScript(input: ShellScriptInput): string {
	const lines: string[] = [
		"#!/bin/sh",
		// #62: the name is untrusted (imported presets) — one line, no controls.
		`# llama-deck preset: ${sanitizeTextLine(input.presetName)}`,
		"# Generated by llama-deck — review before running.",
		"",
	];
	for (const [key, value] of Object.entries(input.envVars)) {
		// #62: invalid identifiers cannot be exported safely — skipped.
		if (!isValidEnvKey(key)) continue;
		lines.push(`export ${key}=${formatEnvValue(value, "shell")}`);
	}
	lines.push(
		`exec ${formatCommand(input.built.command, input.built.args, "shell")}`,
	);
	return `${lines.join("\n")}\n`;
}
