/**
 * .sh exporter (§3.3, P4-FR-16b): POSIX script with env vars + exec.
 * Output is deterministic — golden-file tested (P4-NFR-01 spirit).
 */

import type { BuiltCommand } from "../flags/builder";
import { formatCommand, formatEnvValue } from "./quote";

export interface ShellScriptInput {
	built: BuiltCommand;
	envVars: Record<string, string>;
	presetName: string;
}

export function buildShellScript(input: ShellScriptInput): string {
	const lines: string[] = [
		"#!/bin/sh",
		`# llama-deck preset: ${input.presetName}`,
		"# Generated by llama-deck — review before running.",
		"",
	];
	for (const [key, value] of Object.entries(input.envVars)) {
		lines.push(`export ${key}=${formatEnvValue(value, "shell")}`);
	}
	lines.push(
		`exec ${formatCommand(input.built.command, input.built.args, "shell")}`,
	);
	return `${lines.join("\n")}\n`;
}
